# -*- coding: utf-8 -*-
"""PTTT - Lab07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHbGEfImiivvGBya16Qg5qch1FvduGA4
"""

from random import randint
from math import ceil

# Tìm phần tử lấn chiếm cấp độ 10
def findNum(array):
  store = {}
  for n in array:
    if n in store.keys():
      store[n] += 1
    else:
      store[n] = 1
  
  result = []
  for key in store.keys():
    if store[key] >= ceil(len(array) / 10):
      result.append(key)
  
  return result

input_array = [randint(0, 10) for i in range(100)]
print(findNum(input_array))

def merge_array(A, B):
  result = []
  n1 = len(A)
  n2 = len(B)
  i = 0
  j = 0

  while i < n1 and j < n2:
    if A[i] < B[j]:
      result.append(A[i])
      i += 1
    elif A[i] > B[j]:
      result.append(B[j])
      j += 1
    else:
      result.append(A[i])
      result.append(B[j])
      i += 1
      j += 1

  while i < n1:
    result.append(A[i])
    i += 1
  while j < n2:
    result.append(B[j])
    j += 1

  return result

A = [1,3,5,6,7]
B = [3,4,8,9,10]
print(merge_array(A, B))