# -*- coding: utf-8 -*-
"""Phân tích thuật toán - Lab01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQxq_8C5YwZLkvaoSZGIru--6U2G94Sb
"""

def DecToBi():
  n = int(input('Nhập n > 0: '))
  result = ''
  while (n > 0):
    result = str(n%2) + result
    n = n // 2
  print(result)

DecToBi()

import numpy as np
import matplotlib.pyplot as plt

def DecToBi_and_draw():
  decimal_array = np.arange(100, 1001, 100)

  gan_list = list()
  sosanh_list = list()
  log2_list = np.log2(decimal_array)

  for n in decimal_array:
    gan = 0
    sosanh = 1
    result = ''
    while (n > 0):
      result = str(n%2) + result
      n = n // 2
      gan += 2
      sosanh += 1
    gan_list.append(gan)
    sosanh_list.append(sosanh)

  plt.figure(figsize=(8, 8))
  plt.plot(decimal_array, log2_list, label = "log2(N)")
  plt.plot(decimal_array, gan_list, label = "gan(N)")
  plt.plot(decimal_array, sosanh_list, label = "sosanh(N)")
  plt.legend()
  plt.show()

DecToBi_and_draw()