# -*- coding: utf-8 -*-
"""PTTT - Lab06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yOXJx5Qg8Fx4ixZyV0Q6ymkre7Kq9sKN
"""

from random import randint

N = [i for i in range(50, 1001, 50)]

A = list()
for n in N:
  temp = list()
  while len(temp) < n:
    a = randint(0, 500)
    temp.append(a)
  A.append(temp)

def knapsack(A, S):
  ## Mảng L cho biết có tính được tổng S không? Nếu L[S] = 1 thì được, L[0] != 1 thì không.
  L = [0] * (S + 1)
  L[0] = 1

  ## Mảng H dùng để truy vết. Để tính được tổng S thì ta phải có tổng H[S].
  H = [0] * (S + 1)

  ## Fill mảng L và H
  for i in range(len(A)):
    for j in range(S, A[i] - 1, -1):
      if (L[j] == 0) and (L[j - A[i]] == 1):
        L[j] = 1
        H[j] = j - A[i]

  ## Trả kết quả
  if L[S] != 1: return -1
  else:
    i = S
    temp = list()
    while i > 0:
      temp.append(i - H[i])
      i = H[i]
  return temp

S = 200
for a in A:
  print(f"A = {set(a)}\nSubset = {knapsack(list(set(a)), S)}\n")